### ISSUE TITLE
Syphon Texture not showing in latest builds.

### ISSUE THREAD

**Issue by DanielArnett** [WilstonOreo/omnidome#13]
I'm building from source but Syphon is not building with it. 

![screen shot 2016-06-09 at 12 12 44 pm](https://cloud.githubusercontent.com/assets/3029502/15937083/8d810d2e-2e3b-11e6-8698-6a9591fec907.png)

`make[1]: *** [CMakeFiles/plugin_input_Syphon.dir/all] Error 2`
and a bunch of 
`SyphonNameboundClient.h:0: Note: No relevant classes found. No output generated.`

On a separate note; when I try to use Syphon in Release 1 I can see my Syphon server names but when I select the server I want to use nothing shows up.

**Comment by WilstonOreo** [comment]
This was a problem in the cm8kr build system, I fixed that a few days ago, you should pull the newest version of cm8kr ;)

**Comment by DanielArnett** [comment]
Okay that did the trick, however now I'm back to Syphon not displaying textures.

![screen shot 2016-06-10 at 11 09 20 am](https://cloud.githubusercontent.com/assets/3029502/15968974/e134bbee-2efb-11e6-8011-f9644023925a.png)

Notice on the left that Omnidome is identifying my video server, however the texture is not displaying on the dome, and was not projecting. I don't see errors in the terminal, however I do encounter segmentation faults occasionally when adding and removing a Syphon source.

**Comment by WilstonOreo** [comment]
Seg faults never happened with VDMX syphon server, i guess the texture target in Arena might be a GL_TEXTURE_2D and not GL_TEXTURE_RECTANGLE as in VDMX. Guess I have to install Arena and test it here

**Comment by DanielArnett** [comment]
VDMX behaves the same for me.

![screen shot 2016-06-10 at 11 32 16 am](https://cloud.githubusercontent.com/assets/3029502/15969737/4d0492b0-2eff-11e6-9836-51584768fa8e.png)

**Comment by DanielArnett** [comment]
How can I debug this? I'd like to see why mine is behaving differently than yours. For reference I'm using a Late 2013 Mac Pro with OSX 10.9.5.

**Comment by WilstonOreo** [comment]
We havent tested it on 10.9.5, but what I can already tell by looking at the screen shot is that the OpenGL texture id the syphon input returns is still 0, so there is no texture received. Weird.

**Comment by DanielArnett** [comment]
I assume Syphon::update() is where the frame is updated, but the program never reaches my breakpoints there. Otherwise my IDE and debugging seem to be working fine :)

When is update() supposed to run?

**Comment by WilstonOreo** [comment]
The update method is triggered by the timer.
Does the ::activate method get called?
Whats the value of the isSetup_ variable?

**Comment by DanielArnett** [comment]
The ::activate method is called when I select Syphon, isSetup_ is initially
set to false then switches to true as it appears it should.

**Comment by DanielArnett** [comment]
![screen shot 2016-06-19 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/3029502/16179377/be737a5e-3631-11e6-923f-c2c7253b7824.png)

Ultimately I believe Line 81 is where the problem lies. I am not familiar with Objective C, so this is entirely dark magic to me, but the issue is that the void pointer `client_` is not set properly on line 81.
```[(SyphonNameboundClient*)client_ lockClient];```

![screen shot 2016-06-19 at 3 25 27 pm](https://cloud.githubusercontent.com/assets/3029502/16179403/90327ef0-3632-11e6-80ea-9c24b2ef4872.png)

**Comment by WilstonOreo** [comment]
Interesting, I will check some other reference implementations tomorrow, maybe the bug is on me, maybe on syphon framework ;)

**Comment by DanielArnett** [comment]
Also I will try updating my syphon framework, I installed it over a year
ago so it could be outdated.

**Comment by DanielArnett** [comment]
Have you checked the reference implementations? Do you have any links to c++ implementations I could look at?

**Comment by WilstonOreo** [comment]
I used these ones:
https://github.com/Syphon/Unity3D/blob/master/Syphon%20Implementations/Unity3D/Unity3D-3_5/SyphonUnityPlugin/SyphonUnity.mm
https://github.com/astellato/Cinder-Syphon/blob/master/src/syphonClient.mm
https://github.com/astellato/ofxSyphon/blob/master/src/ofxSyphonClient.mm

Compare it to the bind method in the above implementations, it pretty similar to Omnidome's.

**Comment by DanielArnett** [comment]
Yes, astellato's implementation is identical however the unity 3d
implementation does not seem similar. Perhaps I should try building some of
Astellato's work and see if syphon works correctly using his identical
implementation.

It's something to work from, thanks!
On Jun 21, 2016 08:46, "Wilston Oreo" <notifications@github.com> wrote:

I used these ones:
https://github.com/Syphon/Unity3D/blob/master/Syphon%20Implementations/Unity3D/Unity3D-3_5/SyphonUnityPlugin/SyphonUnity.mm
https://github.com/astellato/Cinder-Syphon/blob/master/src/syphonClient.mm
https://github.com/astellato/ofxSyphon/blob/master/src/ofxSyphonClient.mm

Compare it to the bind method in the above implementations, it pretty
similar to Omnidome's.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cr8tr/omnidome/issues/13#issuecomment-227428503>, or mute
the thread
<https://github.com/notifications/unsubscribe/AC45_lHjtmJhb_DMHIHg-dhWWTI7-dbsks5qN90igaJpZM4IyJpL>
.

**Comment by DanielArnett** [comment]
Okay, I've tested on another machine and syphon seems to be working fine. I'll try updating/reverting my computer until I get it to work. What OSX version do you use it with? Has it been tested with El Capitan? Should I try updating to that? I'll set up time machine and give it a try.

**Comment by WilstonOreo** [comment]
We tested it both with El Capitan and Yosemite.

**Comment by DanielArnett** [comment]
Sweet, installing El Capitan now. Is it documented anywhere what the recommended OSX version is, or did I miss that?

**Comment by WilstonOreo** [comment]
No, it not documented, will do ;)

**Comment by DanielArnett** [comment]
Well that did it! I updated from Mavericks to El Capitan and Syphon is now fully functional. My planetarium now runs Omnidome! Thank you for all the setup help.

**Comment by DanielArnett** [comment]
This issue has reemerged however only with my Vjing applications.

[Full details in this video here.](https://youtu.be/Vv9uTdfZfW8)

Attached are my outputs, both standard and error. Omnidome releases properly, but syphon doesn't work.
[stderr.txt](https://github.com/cr8tr/omnidome/files/429072/stderr.txt)
[stdout.txt](https://github.com/cr8tr/omnidome/files/429071/stdout.txt)

**Comment by gum-control** [comment]
I'm also having a problem getting a Syphon stream into Omnidome. I'm able to get a stream into a Syphon client via Max/Jitter but it does not appear in Omnidome when I add the Syphon input.

I'm using Omnidome v1.0.0 for Mac, running OS 10.9.5

Any help on troubleshooting would be much appreciated. Thanks.

**Comment by DanielArnett** [comment]
I would recommend that you update your OS. That's what solved it for me in
release 1.0. My problem is that now I have a similar issue when compiling
the latest version.

**Comment by gum-control** [comment]
Thanks for the tip. Unfortunately I can't risk the upgrade to El Capitan as it appears Apple is dedicated to making its OS less functional these days. I'll seek solutions inside Max for now.

**Comment by gum-control** [comment]
Quick update: I ran Omnidome on a Yosemite iMac at work today and the Syphon stream worked fine. So it does appear there's a bug when running this in Mavericks.
