### ISSUE TITLE
Processing Syphon Issue

### ISSUE THREAD

**Issue by foong** [WilstonOreo/omnidome#26]
Has anyone have any issues with processing to omnidome?
I have tried a simple sendFrame to omnidome but the texture doesn't show.
However the simple server seems to be working fine.

MacBook Pro (15-inch, Mid 2010)
Elcapitan

![screen shot 2016-11-16 at 4 22 10 pm](https://cloud.githubusercontent.com/assets/12502272/20339752/193a6a8a-ac19-11e6-98fb-4a6704a4d7a9.png)
![screen shot 2016-11-16 at 4 22 42 pm](https://cloud.githubusercontent.com/assets/12502272/20339754/1b71a3ea-ac19-11e6-99b5-3879b28ac392.png)

**Comment by brocro** [comment]
Yeah, i can confirm that this doesn't seem to work with Omnidome at the moment. It does work directly with VDMX though so i assume it is a problem on the Omnidome side. Will try and look into it.

![processing_syphon](https://cloud.githubusercontent.com/assets/17926886/20346627/6ab00206-abfd-11e6-961d-e9a781ddb8ae.png)

**Comment by foong** [comment]
Hey, any updates on this? or anyone managed to hack this to work?

**Comment by brocro** [comment]
not yet, sorry. we will try and get to it soon though.

**Comment by WilstonOreo** [comment]
Hi, I was able to reproduce and fix it and push it yesterday. The fix will be in the next omnidome release.

**Comment by foong** [comment]
thanks! Looking forward to it!
