### ISSUE TITLE
Quick Submodule Fix

### ISSUE THREAD

**Issue by DanielArnett** [WilstonOreo/omnidome#29]
When I try to update the submodules (OpenMesh and omnicalib) omnicalib does not download properly.

Fix:
Open .gitmodules and replace the line `url = git@github.com:WilstonOreo/omnicalib.git` with `url = https://github.com/WilstonOreo/omnicalib.git`.

**Comment by WilstonOreo** [comment]
You need to setup an SSH key for github, then it should work.

**Comment by DanielArnett** [comment]
I needed to sign in to git on my machine to clone from github. The OpenMesh issue was actually my universities firewall blocking the website, had to vpn out of the university, then everything worked fine.
