### ISSUE TITLE
Omnidome not detecting 1of the 4 projectors (AMD drivers)

### ISSUE THREAD

**Issue by bhavnayaddav** [WilstonOreo/omnidome#31]
Hi Team,

We have a setup where in one monitor (1280X1024) and 4 projectors (each set to 1920X1200) are present. We have used Omnidome installable on OS - Linux Debian Jessie and Driver - AMD Radeon R9 for this configuration.

Surprisingly, one of the projectors is not picked up by Omnidome. For identifying the root cause, we ran a few images and videos without Omnidome and all the projectors worked well. 

Any pointers on investigating and fixing this problem would be helpful. Thanks!!

**Comment by brocro** [comment]
Hi, 

Can i ask how you have the 4 projectors configured in Debian? is it in an xinerama single display made of multiple projectors combined into a single display? The 1920 x 1200 resolution is not one we've tested, it should work if it's a 4:1 ratio but sometimes using different resolutions can cause an issue. Is it possible to test it with a different set of resolutions, i.e 1920 x 1080 or 1280 x 800 just to see if it's still happening? 

Please let me know if this isn't working and we'll try and look into it.

**Comment by WilstonOreo** [comment]
Hi, thanks for the bug report. But since I dont have a Radeon R9 available, I cannot easily reproduce the bug. Can you try to find out the geometry of the projector screens?

**Comment by bhavnayaddav** [comment]
@brocro - Yes, it is a single display made of multiple projectors combined. I will give a try with the modified resolutions.

@WilstonOreo - The projector screen is a hemispherical dome (diameter 1.86 m).

**Comment by bhavnayaddav** [comment]
@brocro , @WilstonOreo - Setting the monitor as a primary display solved this problem. I reckon that the projector, that was not getting picked by Omnidome, was somehow treated as a primary display. Using xrandr I set the monitor to be a primary display, restarted the machine and voila!

Thanks for the pointer to dig in the display configurations.

**Comment by brocro** [comment]
No problem! Good to hear it's working now.
