### ISSUE TITLE
CMake Error at cmake-scripts/base/build_target.cmake:111 (QT5_WRAP_CPP):   Unknown CMake command "QT5_WRAP_CPP".

### ISSUE THREAD

**Issue by GregFinger** [WilstonOreo/omnidome#33]
macOS Sierra 10.12.4
QT 5.7

When running the bootstrip.sh, i get this error (commit from Apr 4, 2017)
`
CMake Error at cmake-scripts/base/build_target.cmake:111 (QT5_WRAP_CPP):
  Unknown CMake command "QT5_WRAP_CPP".
`

I just tried a previous version i had on my computer already (the file dates were Jan 10, 2017) and bootstrap ran without any errors.

**Comment by WilstonOreo** [comment]
in cmake-scripts/qt.cmake, line 37:
omni_option(QT_MINOR_VERSION "Qt Minor Version" 8 )
Replace the 8 with 7, but I suggest you update Qt to 5.8 ;)

**Comment by WilstonOreo** [comment]
Btw I'm about to switch the build system QMake, so no more CMake hassle.

**Comment by GregFinger** [comment]
Ok, i'll upgrade to 5.8, but before i do, I have a quick question. When using the Qt installer and choosing Qt 5.8, i'm presented with a bunch of options for which components to install (MacOS, iOS, android, etc.)

What are the minimum amount of components i need to install to compile Omnidome? I'm guessing i need the macOS, but then having the Qt WebEngine selected as well adds 3GB onto the install, and the WebEngine i probably don't need for Omnidome to compile.

**Comment by WilstonOreo** [comment]
You just need macOS, everything else is not needed.

**Comment by GregFinger** [comment]
Ok, just confirming that replacing the 8 with 7 does indeed fix the problem, but in the end i deleted everything, and started from fresh with Qt 5.8 and everything was successful. Thank you.
