### ISSUE TITLE
Qt 5.9 Will it Work?

### ISSUE THREAD

**Issue by kr15h** [WilstonOreo/omnidome#35]
Hello comrades!

Will it work with Qt 5.9? Gonna test it now myself, but just asking.

**Comment by WilstonOreo** [comment]
Yes, definitely. The current and next version work with 5.9.

**Comment by kr15h** [comment]
Are there any license related issues I should keep in mind when using trial version of Qt when compiling? After the compilation is done and the software works. What should one be aware of?
