### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Kleemensch** [WilstonOreo/omnidome#37]
my system: osx El Capitan 10.11.3
cmake version 3.9.2
Qt version 5.9.1

i installed brew, installed Cmake, installed latest QT, 
Github had Problems with downloading omnicalib-(there was no download link) > files were downloaded one by one, and put in place. (i suspect a problem)
got open mesh-> added submodules manually (bootstrap script did not work).. so far so good

this is the error i get:

Lari-Faris-MBP:omnidome larifari$ cmake . -DQT_PATH=/Users/larifari/Qt5.9.1
-- Found omni environment in /Users/larifari/omnidome/cmake-scripts
-- Build mode is Debug
-- C compiler is /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- C++ compiler is /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Setup build directories...
CMake Deprecation Warning at cmake-scripts/base/add_submodule.cmake:34 (cmake_policy):
  The OLD behavior for policy CMP0022 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:19 (omni_add_submodule)

Adding submodule omnicalib
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Omnidome 1.0.1
CMake Error at cmake-scripts/base/build_target.cmake:111 (QT5_WRAP_CPP):
  Unknown CMake command "QT5_WRAP_CPP".
Call Stack (most recent call first):
  cmake-scripts/base/build_target.cmake:127 (omni_setup_build_target)
  CMakeLists.txt:36 (omni_add_shared_library)

-- Configuring incomplete, errors occurred!
See also "/Users/larifari/omnidome/CMakeFiles/CMakeOutput.log".
Lari-Faris-MBP:omnidome larifari$

**Comment by brocro** [comment]
so here is how to fix this issue (assuming you are on mac osx and have the latest version of Qt - 5.9.2)

in the file qt.cmake - line 37

omni_option(QT_MINOR_VERSION "Qt Minor Version" 9.2 )

then run the bootstrap.sh file (you need a github account with a valid ssh key)

**Comment by Kleemensch** [comment]
Ahh awesome, i will try that soon..
Unfortunately i had to buy  blendy dome VJ last week :D Next week is our Presentation.
Damn :) 


Thanks and Greetings from Hannover,
Klemens
